// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelegramBot.DbAccess;

namespace KosarRB_Bot.Migrations
{
    [DbContext(typeof(TelegramBotContext))]
    partial class TelegramBotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TelegramBot.Models.BotMessage", b =>
                {
                    b.Property<int>("fldid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("fldMes")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("fldMobileNumberOrId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("fldOK")
                        .HasColumnType("int");

                    b.Property<string>("fldResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("fldSendTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("fldTime")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("flddate")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("fldid");

                    b.ToTable("tblBotMessage");
                });

            modelBuilder.Entity("TelegramBot.Models.ContactInfo", b =>
                {
                    b.Property<long>("fldChatId")
                        .HasColumnType("bigint");

                    b.Property<int>("fldChatState")
                        .HasColumnType("int");

                    b.Property<int>("fldChatType")
                        .HasColumnType("int");

                    b.Property<string>("fldMobileNumberOrId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("fldChatId");

                    b.ToTable("tblContactInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
